### ISSUE TITLE
Create content in markdown 

### ISSUE THREAD

**Issue by fccoelho** [Mosqlimate-project/Mosqlimate-project.github.io#10]
@eltonn,  I noticed that you have been adding the content to the site as HTML in the template. 

I think this should be done as markdown files as described here: https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown to facilitate maintenance.

**Comment by fccoelho** [comment]
Pinging @eltonn about this bug.

**Comment by eltonn** [comment]
@fccoelho ,
yesterday I invested more time in this adjustment and the task does not evolve and I do not know if I will be able to evolve. So I already signal you that I won't make it.

**Comment by fccoelho** [comment]
Thank you @eltonn  for letting me know about this. I'll have someone else look at this.
